{% set name = "humbug" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/humbug-{{ version }}.tar.gz
  sha256: efa09dce7e88a49ae14d6456e4b754c11fbe69ccd9c9cf6f8c6bec245e4b88b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests

test:
  imports:
    - humbug
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bugout-dev/humbug
  summary: 'Humbug: Do you build developer tools? Humbug helps you know your users.'
  license_file: LICENSE
  license: Apache-2.0
  dev_url: https://github.com/bugout-dev/humbug/tree/main/python
  doc_url: https://github.com/bugout-dev/humbug/tree/main/python
  description: |
    Humbug lets you collect basic system information and crash reports while
     respecting your users' privacy. In addition to getting reports, you get to
     be GDPR-compliant from day one.

extra:
  recipe-maintainers:
    - thewchan
